import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  es: {
    'nav.data_panel': 'Panel de Datos',
    'nav.control': 'Panel de Control',
    'nav.prediction': 'Predicción Inteligente',
    'nav.prediction_summary': 'Resumen de Predicción',
    'nav.param_config': 'Configuración de Parámetros',
    'nav.prediction_comparison': 'Comparación de Resultados',
    'nav.alerts': 'Centro de Alertas',
    'nav.inventory_mgmt': 'Gestión de Inventario',
    'nav.performance': 'Análisis de Desempeño',
    'nav.hospital_perf': 'Desempeño del Hospital',
    'nav.provider_perf': 'Desempeño del Proveedor',
    'nav.basic_info': 'Información Básica',
    'nav.med_info': 'Información de Medicamentos',
    'nav.pharm_info': 'Información de Farmacia',
    'nav.prov_info': 'Información de Proveedor',
    'nav.ai_assistant': 'Asistente de IA',
    'nav.inv_details': 'Detalles de Inventario',
    'nav.cons_analysis': 'Análisis de Consumo',
    'nav.inv_inbound': 'Gestión de Ingresos',
    'nav.inv_expiry': 'Gestión de Caducidad',
    'nav.replenish_smart': 'Reabastecimiento Inteligente',
    'nav.replenish_mgmt': 'Gestión de Reabastecimiento',
    'nav.shipment_mgmt': 'Gestión de Envíos',
    'nav.supply_tracking': 'Seguimiento de Suministro',
    'dashboard.title': 'Centro Inteligente de Cadena de Suministro',
    'dashboard.hospitals_count': 'Hospitales',
    'dashboard.stock_insufficient': 'Stock Insuficiente',
    'dashboard.replenish_rec': 'Reabastecimiento Recomendado',
    'dashboard.stock_sufficient': 'Stock Suficiente',
    'dashboard.providers_count': 'Proveedor',
    'dashboard.header.admin_console': 'Consola de Administración',
    'dashboard.header.logout': 'Cerrar sesión',
    'dashboard.total_consumption': 'Consumo Total',
    'dashboard.avg_monthly_consumption': 'Consumo Promedio Mensual',
    'dashboard.annual_consumption': 'Consumo Anual',
    'dashboard.comparison_annual': 'Comparación Anual (Interanual)',
    'dashboard.comparison_monthly': 'Comparación Mensual',
    'dashboard.inventory_turnover': 'Rotación de Inventario',
    'dashboard.stock_out_state': 'Estado de Faltantes',
    'dashboard.stock_turnover_rate': 'Tasa de Rotación de Inventario',
    'dashboard.medicine_proportion': 'Proporción de Medicamentos',
    'dashboard.med_proportions': 'Proporción de Medicamentos',
    'dashboard.provider_rankings': 'Ranking de Proveedores',
    'dashboard.med_emergency': 'Medicamentos de Emergencia',
    'dashboard.med_antiinfective': 'Antiinfecciosos',
    'dashboard.med_chronic': 'Medicamentos para Enfermedades Crónicas',
    'dashboard.med_other': 'Otros',
    'dashboard.income_trend': 'Tendencia de Ingresos',
    'dashboard.med_inventory': 'Inventario de Medicamentos',
    'dashboard.table.status': 'Estado',
    'dashboard.table.med_name': 'Nombre del Medicamento',
    'dashboard.table.est_replenish_date': 'Próxima Fecha Estimada de Reabastecimiento',
    'dashboard.table.days_left': 'Días Disponibles Restantes',
    'dashboard.table.current_inv': 'Inventario Actual',
    'dashboard.table.stock_min': 'Stock Mínimo',
    'dashboard.table.stock_opt': 'Stock Óptimo',
    'dashboard.table.stock_max': 'Stock Máximo',
    'dashboard.status.low_stock': 'Stock bajo',
    'dashboard.status.replenish': 'Reabastecer',
    'dashboard.med.amoxicillin': 'Cápsulas de Amoxicilina',
    'dashboard.med.metformin': 'Tabletas de Clorhidrato de Metformina',
    'dashboard.med.nifedipine': 'Tabletas de Liberación Prolongada de Nifedipina',
    'dashboard.med.amlodipine': 'Tabletas de Amlodipino y Benazepril',
    'dashboard.hospitals': 'Hospitales',
    'dashboard.medicines': 'Medicamentos',
    'dashboard.year_2025': 'Año 2025',
    'dashboard.january': 'Enero',
    'dashboard.score': 'Puntuación',
    'dashboard.hospital_regional': 'Hospital Regional',
    'dashboard.consumption_total': 'Consumo Total',
    'dashboard.consumption_avg': 'Promedio Mensual',
    'dashboard.consumption_annual': 'Consumo Anual',
    'dashboard.inventory_rotation': 'Rotación de Inventario',
    'dashboard.inventory_status': 'Estado de Faltantes',
    'dashboard.delivery_rate': 'Tasa de Entrega',
    'dashboard.compliance': 'Cumplimiento',
    'dashboard.alerts': 'Estadísticas de Alerta',
    'dashboard.alert.low_stock': 'Stock Bajo',
    'dashboard.alert.expiring': 'Próximo a Vencer',
    'dashboard.alert.usage_anomaly': 'Anomalía de Consumo',
    'dashboard.alert.supply_delay': 'Retraso en Suministro',
    'dashboard.alert.quality_issue': 'Problema de Calidad',
    'dashboard.ai_vision': 'AI Visión Operativa',
    'dashboard.see_all': 'Ver Todo',
    'dashboard.ai.trends': 'Análisis de Tendencias de Consumo',
    'dashboard.ai.trends_desc': 'Según el análisis de los últimos 3 meses, el consumo de antibióticos muestra fluctuaciones estacionales. Se prevé un aumento del 15% el próximo mes. Se recomienda realizar compras anticipadas.',
    'dashboard.ai.optimization': 'Sugerencias de Optimización de Compras',
    'dashboard.ai.optimization_desc': 'Se detectó una frecuencia de compra excesiva en 5 medicamentos. Se recomienda cambiar a un modelo de compra por lotes, lo que puede ahorrar un 8% en logística y un 12% en gestión',
    'dashboard.ai.expiry': 'Recordatorio de Gestión de Caducidad',
    'dashboard.ai.expiry_desc': 'El sistema ha detectado que 8 medicamentos en 3 hospitales caducarán en los próximos 60 días. Se recomienda redistribuir el inventario priorizando los hospitales con mayor consumo.',
    'dashboard.ai.provider': 'Alerta de Riesgo del Proveedor',
    'dashboard.ai.provider_desc': 'Según datos históricos del proveedor, Farmacéutica Chinoin puede tener retrasos en entregas. Se recomienda buscar proveedores alternativos para 4 productos suministrados.',
    'hospital.gen': 'Hospital General de México',
    'hospital.abc': 'Centro Médico ABC',
    'hospital.can': 'Instituto Nacional de Cancerología',
    'hospital.izt': 'Hospital Comunitario de Iztapalapa',
    'hospital.santa': 'Hospital Comunitario de Santa Fe',
    'hospital.sur': 'Centro Médico del Sur',
    'hospital.ang': 'Hospital Ángeles (México)',
    'header.all_hospitals': 'Todos los Hospitales',
    'header.admin': 'Admin',
    'dashboard.stats.orders': 'Órdenes Especiales',
    'dashboard.stats.expiring': 'Próximos a Vencer',
    'dashboard.stats.suggestions': 'Sugerencias Compra',
    'dashboard.stats.reserves': 'Reservas Especiales',
    'dashboard.inventory_summary': 'Resumen de Inventario',
    'dashboard.task_list': 'Lista de Tareas',
    'dashboard.notifications': 'Notificaciones',
    'dashboard.hospital_state': 'Estado del Inventario Hospitalario',
    'prediction.reforecast': 'Repronosticar',
    'prediction.last_result': 'Último Resultado',
    'prediction.total_meds': 'Total Medicamentos',
    'prediction.accuracy': 'Precisión Pronóstico',
    'prediction.optimization': 'Tasa Optimización',
    'prediction.alerts': 'En Alerta',
    'prediction.detail_subtitle': 'Detalles del Pronóstico de Medicamento',
    'prediction.replenishment_planned': 'Reposición prevista',
    'prediction.forecast_accuracy': 'Precisión de Pronóstico',
    'prediction.expected_consumption': 'Consumo Previsto',
    'prediction.available_stock': 'Stock Disponible',
    'prediction.monthly_avg_consumption': 'Consumo Promedio Mensual',
    'prediction.min_stock': 'Stock Mínimo',
    'prediction.max_stock': 'Stock Máximo',
    'prediction.optimal_stock': 'Stock Óptimo',
    'prediction.last_entry': 'Última Entrada',
    'prediction.analysis_title': 'Análisis de Pronóstico',
    'prediction.provider': 'Proveedor',
    'prediction.lead_time': 'Plazo de Entrega',
    'prediction.confirm_replenishment': 'Confirmar Reabastecimiento',
    'prediction.modify_quantity': 'Modificar Cantidad',
    'prediction.change_provider': 'Cambiar Proveedor',
    'prediction.view_details': 'Ver Detalles',
    'prediction.detail_title': 'Detalles del Pronóstico',
    'params.title': 'Parametrización',
    'params.save': 'Guardar Cambios',
    'params.reset': 'Reset',
    'params.window': 'Ventana Temporal',
    'params.safety_factor': 'Factor de Seguridad',
    'params.seasonal': 'Influencia Estacional',
    'params.stability': 'Estabilidad del Suministro',
    'params.impact_analysis': 'Análisis de Impacto',
    'common.view_all': 'Ver Todo',
    'common.manage': 'Gestionar',
    'common.back': 'Volver al Panel',
    'common.week': 'Semana',
    'common.month': 'Mes',
    'common.quarter': 'Trimestre',
    'day.mon': 'Lun',
    'day.tue': 'Mar',
    'day.wed': 'Mie',
    'day.thu': 'Jue',
    'day.fri': 'Vie',
    'day.sat': 'Sab',
    'day.sun': 'Dom',
    'placeholder.module_prepping': 'Estamos preparando el módulo de ',
    'placeholder.explore_control': '. Explora el Panel de Control para datos en tiempo real.',
    'common.id_generic': 'ID genérico',
    'common.name_generic': 'Nombre genérico',
    'common.name_commercial': 'Nombre comercial',
    'common.specification': 'Especificación',
    'common.brand': 'Marca',
    'common.actions': 'Acciones',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.details': 'Detalles',
    'common.add_medication': 'Añadir medicamento',
    'common.add_pharmacy': 'Agregar Farmacia',
    'common.add_provider': 'Agregar Proveedor',
    'common.total_records': 'Total {count} Records',
    'common.jump_to': 'Jump to',
    'common.records_per_page': '/ page',
    'common.month_change': 'Cambio Mensual',
    'common.previous_period': 'vs. período anterior',
    'common.search': 'Buscar',
    'common.update': 'Actualizar',
    'common.export': 'Exportar',
    'common.new_order': 'Nueva Orden',
    'common.total_records_count': 'Total {count} Records',
    'common.status': 'Estado',
    'common.alert_type': 'Tipo de Anomalía',
    'common.hospital': 'Hospital',
    'common.indicator': 'Indicador',
    'common.actual_value': 'Valor Actual',
    'common.ref_value': 'Valor de Referencia',
    'common.deviation_rate': 'Tasa de Desviación',
    'replenish.pending_approval': 'Pendiente de aprobación',
    'replenish.pending_shipment': 'Pendiente de envío',
    'replenish.in_transit': 'En Transporte',
    'replenish.confirm_receipt': 'Confirmar recepción',
    'replenish.order_status': 'Estado del Pedido',
    'replenish.order_no': 'Nº de Orden de Reabastecimiento',
    'replenish.med_name': 'Nombre del Medicamento',
    'replenish.quantity_requested': 'Cantidad Solicitada',
    'replenish.expected_delivery': 'Fecha de Entrega Esperada',
    'replenish.new_replenish_order': 'Nueva Orden de Reabastecimiento',
    'shipment.shipment_date': 'Fecha de Envío',
    'shipment.shipment_status': 'Estado del Envío',
    'shipment.shipment_no': 'Nº de Envío',
    'shipment.lot_no': 'Número de Lote',
    'shipment.receiving_hospital': 'Hospital Receptor',
    'shipment.actual_quantity': 'Cantidad Entregada Real',
    'shipment.actual_delivery_date': 'Fecha Real de Envío',
    'shipment.print': 'Imprimir',
    'supply.orders_in_transit': 'Órdenes en Tránsito',
    'supply.on_time_delivery_rate': 'Tasa de Entrega Puntual',
    'supply.orders_with_anomalies': 'Órdenes con Anomalías',
    'supply.late_delivery': 'Entrega Tardía',
    'supply.order_no': 'Nº de Orden de Reabastecimiento',
    'supply.provider_id': 'ID del Proveedor',
    'supply.med_info': 'Información del Medicamento',
    'supply.order_amount': 'Importe del Pedido',
    'supply.delivery_stats': 'Estadísticas de Entrega por Proveedor',
    'supply.anomaly_analysis': 'Análisis de Órdenes con Anomalías',
    'supply.delay': 'Retraso en el Envío',
    'supply.damaged_packaging': 'Embalaje Dañado',
    'supply.incorrect_quantity': 'Cantidad Incorrecta',
    'supply.quality_issue': 'Problema de Calidad',
    'hospital.rotation_index': 'Índice de Rotación de Inventario',
    'hospital.rupture_rate': 'Tasa de Ruptura de Stock',
    'hospital.rational_use': 'Uso Racional de Medicamentos',
    'hospital.savings_rate': 'Tasa de Ahorro en Costos de Compra',
    'hospital.performance_comparison': 'Comparativa de Desempeño entre Hospitales',
    'hospital.historical_trends': 'Análisis de Tendencias Históricas',
    'hospital.anomaly_alerts': 'Alertas de Anomalías de Desempeño',
    'provider.on_time_delivery': 'Tasa de Entrega Puntual',
    'provider.order_fulfillment': 'Tasa de Cumplimiento de Pedidos',
    'provider.approved_quality': 'Tasa de Calidad Aprobada',
    'provider.response_capacity': 'Capacidad de Respuesta del Proveedor',
    'provider.classification': 'Clasificación General de Proveedores',
    'provider.trend': 'Tendencia de Desempeño',
    'provider.anomaly_alerts': 'Alertas de Anomalías',
    'common.reset': 'Restablecer',
    'common.search_btn': 'Buscar',
    'alerts.total': 'Total de Alertas',
    'alerts.pending': 'Alertas Pendientes',
    'alerts.resolved': 'Alertas Resueltas',
    'alerts.resolution_rate': 'Tasa de Resolución',
    'alerts.list_title': 'Lista de Alertas',
    'alerts.level': 'Nivel de Alerta',
    'alerts.time': 'Hora de Alerta',
    'alerts.type': 'Tipo de Alerta',
    'alerts.med_name': 'Nombre del Medicamento',
    'alerts.stock_available': 'Stock Disponible',
    'alerts.stock_min': 'Stock Mínimo',
    'alerts.critical': 'Crítica',
    'alerts.important': 'Importante',
    'alerts.normal': 'Normal',
    'alerts.low_stock': 'Stock Bajo',
    'alerts.replenish': 'Reabastecer',
    'alerts.sufficient': 'Suficiente',
    'pharmacy.status': 'Estado',
    'pharmacy.name': 'Nombre del hospital',
    'pharmacy.location': 'Ubicación/Región',
    'pharmacy.type': 'Tipo de hospital',
    'pharmacy.responsible': 'Responsable',
    'provider.cooperation': 'Estado de cooperación',
    'provider.id': 'ID de proveedor',
    'provider.name': 'Proveedor',
    'provider.contact': 'Persona de contacto',
    'provider.phone': 'Teléfono de contacto',
    'provider.address': 'Dirección',
    'inventory.category_filter': 'Categoría del Medicamento',
    'inventory.hospital_filter': 'Hospital',
    'inventory.status_filter': 'Estado del Inventario',
    'inventory.search_placeholder': 'Buscar por Nombre/ID',
    'inventory.col_status': 'Estado del Inventario',
    'inventory.col_name': 'Nombre del Medicamento',
    'inventory.col_category': 'Categoría del Medicamento',
    'inventory.col_hospital': 'Hospital',
    'inventory.col_stock': 'Stock Disponible',
    'inventory.actions.details': 'Detalles',
    'inventory.actions.edit': 'Editar',
    'inventory.actions.delete': 'Eliminar',
    'consumption.kpi_total': 'Consumo Total',
    'consumption.kpi_avg': 'Consumo Promedio Mensual',
    'consumption.kpi_annual': 'Consumo Anual',
    'consumption.trend_title': 'Análisis de Tendencia de Consumo',
    'consumption.details_title': 'Detalles de Consumo',
    'consumption.col_med': 'Nombre del Medicamento',
    'consumption.col_category': 'Categoría de Medicamento',
    'consumption.col_real': 'Consumo Real',
    'consumption.col_avg': 'Promedio Mensual de Consumo',
    'consumption.col_annual': 'Consumo Anual',
    'inbound.id_filter': 'Fecha de Ingreso',
    'inbound.provider_filter': 'Proveedor',
    'inbound.status_filter': 'Estado de Ingreso',
    'inbound.col_status': 'Estado',
    'inbound.col_id': 'ID de Ingreso',
    'inbound.col_code': 'Código del Medicamento',
    'inbound.col_approval': 'Número de Aprobación',
    'inbound.col_requested': 'Cantidad Solicitada',
    'inbound.col_provider': 'ID del Proveedor',
    'inbound.col_date': 'Fecha de Ingreso',
    'expiry.validity_filter': 'Período de Validez',
    'expiry.status_filter': 'Estado de Vencimiento',
    'expiry.col_status': 'Estado de Vencimiento',
    'expiry.col_med': 'Nombre del Medicamento',
    'expiry.col_lot': 'Número de Lote',
    'expiry.col_validity': 'Período de Validez',
    'expiry.action_transfer': 'Transferencia',
    'expiry.action_promo': 'Promoción',
    'expiry.action_return': 'Devolución',
    'prediction.comparison_report': 'Informe Comparativo de Pronóstico',
    'prediction.cpm_forecast': 'Cantidad Prevista por CPM',
    'prediction.ai_forecast': 'Cantidad Prevista por PharmaLinkAI',
    'prediction.real_consumption': 'Consumo Real',
    'prediction.error_analysis': 'Análisis de Error',
    'prediction.trend_comparison': 'Gráfico Comparativo de Tendencias',
    'prediction.col_med': 'Nombre del Medicamento',
    'prediction.col_hospital': 'Hospital',
    'prediction.col_cpm_forecast': 'Pronóstico CPM',
    'prediction.col_cpm_error': 'Error de CPM',
    'prediction.col_ai_forecast': 'Pronóstico de IA',
    'prediction.col_ai_error': 'Error de IA',
    'prediction.col_real': 'Consumo Real',
    'prediction.col_date': 'Fecha de Pronóstico',
    'prediction.notice_title': 'Aviso',
    'prediction.notice_desc': 'El pronóstico con IA integra tendencias históricas, cambios de inventario, información de proveedores y más, lo que ofrece resultados más precisos que los métodos tradicionales como CPM.',
    'prediction.notice_footer': 'Puede ajustar los parámetros del modelo para mejorar la precisión del pronóstico.',
    'prediction.goto_config': 'Ir a Configuración',
    'ai.assistant_title': 'Asistente de IA',
    'ai.history_title': 'Historial de Conversación',
    'ai.new_chat': 'Nueva Conversación',
    'ai.smart_assistant_header': 'Asistente Inteligente IMSS',
    'ai.smart_assistant_subtitle': 'Su experto en gestión de cadena de suministro médica',
    'ai.card_smart_answers': 'Respuestas inteligentes a preguntas de negocio',
    'ai.card_smart_answers_desc': 'Soporte profesional para gestión de cadena y optimización de inventarios',
    'ai.card_data_analysis': 'Soporte de Análisis de Datos',
    'ai.card_data_analysis_desc': 'Análisis de tendencias, predicciones y recomendaciones basadas en datos históricos',
    'ai.card_report_gen': 'Generación de Informes',
    'ai.card_report_gen_desc': 'Generación automática de informes de inventario y desempeño',
    'ai.suggested_questions': 'Preguntas Sugeridas',
    'ai.input_placeholder': 'Ingrese su pregunta...',
    'ai.chat_default_title': 'Pronóstico de Inventario y Sugerencias de Reposición'
  },
  en: {
    'nav.data_panel': 'Data Panel',
    'nav.control': 'Dashboard',
    'nav.prediction': 'Smart Prediction',
    'nav.prediction_summary': 'Prediction Summary',
    'nav.param_config': 'Parameter Config',
    'nav.prediction_comparison': 'Results Comparison',
    'nav.alerts': 'Alert Center',
    'nav.inventory_mgmt': 'Inventory Management',
    'nav.performance': 'Performance Analysis',
    'nav.hospital_perf': 'Hospital Performance',
    'nav.provider_perf': 'Provider Performance',
    'nav.basic_info': 'Basic Information',
    'nav.med_info': 'Medication Information',
    'nav.pharm_info': 'Pharmacy Information',
    'nav.prov_info': 'Provider Information',
    'nav.ai_assistant': 'AI Assistant',
    'nav.inv_details': 'Inventory Details',
    'nav.cons_analysis': 'Consumption Analysis',
    'nav.inv_inbound': 'Inbound Management',
    'nav.inv_expiry': 'Expiry Management',
    'nav.replenish_smart': 'Smart Replenishment',
    'nav.replenish_mgmt': 'Replenishment Management',
    'nav.shipment_mgmt': 'Shipment Management',
    'nav.supply_tracking': 'Supply Tracking',
    'dashboard.title': 'Smart Supply Chain Command Center',
    'dashboard.hospitals_count': 'Hospitals',
    'dashboard.stock_insufficient': 'Insufficient Stock',
    'dashboard.replenish_rec': 'Recommended Replenishment',
    'dashboard.stock_sufficient': 'Sufficient Stock',
    'dashboard.providers_count': 'Providers',
    'dashboard.header.admin_console': 'Administration Console',
    'dashboard.header.logout': 'Logout',
    'dashboard.total_consumption': 'Total Consumption',
    'dashboard.avg_monthly_consumption': 'Average Monthly Consumption',
    'dashboard.annual_consumption': 'Annual Consumption',
    'dashboard.comparison_annual': 'Annual Comparison (YoY)',
    'dashboard.comparison_monthly': 'Monthly Comparison',
    'dashboard.inventory_turnover': 'Inventory Turnover',
    'dashboard.stock_out_state': 'Shortage Status',
    'dashboard.stock_turnover_rate': 'Inventory Turnover Rate',
    'dashboard.medicine_proportion': 'Medicine Proportion',
    'dashboard.med_proportions': 'Medicine Proportions',
    'dashboard.provider_rankings': 'Provider Rankings',
    'dashboard.med_emergency': 'Emergency Medicines',
    'dashboard.med_antiinfective': 'Anti-infectives',
    'dashboard.med_chronic': 'Chronic Disease Medicines',
    'dashboard.med_other': 'Others',
    'dashboard.income_trend': 'Income Trend',
    'dashboard.med_inventory': 'Medicine Inventory',
    'dashboard.table.status': 'Status',
    'dashboard.table.med_name': 'Medicine Name',
    'dashboard.table.est_replenish_date': 'Next Estimated Replenishment Date',
    'dashboard.table.days_left': 'Days Left',
    'dashboard.table.current_inv': 'Current Inventory',
    'dashboard.table.stock_min': 'Min Stock',
    'dashboard.table.stock_opt': 'Optimal Stock',
    'dashboard.table.stock_max': 'Max Stock',
    'dashboard.status.low_stock': 'Low stock',
    'dashboard.status.replenish': 'Replenish',
    'dashboard.med.amoxicillin': 'Amoxicillin Capsules',
    'dashboard.med.metformin': 'Metformin Hydrochloride Tablets',
    'dashboard.med.nifedipine': 'Nifedipine Extended-Release Tablets',
    'dashboard.med.amlodipine': 'Amlodipine and Benazepril Tablets',
    'dashboard.hospitals': 'Hospitals',
    'dashboard.medicines': 'Medicines',
    'dashboard.year_2025': 'Year 2025',
    'dashboard.january': 'January',
    'dashboard.score': 'Score',
    'dashboard.hospital_regional': 'Regional Hospital',
    'dashboard.consumption_total': 'Total Consumption',
    'dashboard.consumption_avg': 'Monthly Average',
    'dashboard.consumption_annual': 'Annual Consumption',
    'dashboard.inventory_rotation': 'Inventory Turnover',
    'dashboard.inventory_status': 'Shortage Status',
    'dashboard.delivery_rate': 'Delivery Rate',
    'dashboard.compliance': 'Compliance',
    'dashboard.alerts': 'Alert Statistics',
    'dashboard.alert.low_stock': 'Low Stock',
    'dashboard.alert.expiring': 'Expiring Soon',
    'dashboard.alert.usage_anomaly': 'Usage Anomaly',
    'dashboard.alert.supply_delay': 'Supply Delay',
    'dashboard.alert.quality_issue': 'Quality Issue',
    'dashboard.ai_vision': 'AI Operational Vision',
    'dashboard.see_all': 'See All',
    'dashboard.ai.trends': 'Consumption Trend Analysis',
    'dashboard.ai.trends_desc': 'Based on the analysis of the last 3 months, antibiotic consumption shows seasonal fluctuations. A 15% increase is expected next month. Advance purchases are recommended.',
    'dashboard.ai.optimization': 'Purchase Optimization Suggestions',
    'dashboard.ai.optimization_desc': 'Excessive purchase frequency detected in 5 medications. Recommended switching to a batch purchase model, potentially saving 8% in logistics and 12% in management.',
    'dashboard.ai.expiry': 'Expiration Management Reminder',
    'dashboard.ai.expiry_desc': 'The system detected that 8 medications in 3 hospitals will expire in 60 days. Recommended redistributing inventory prioritizing high-consumption hospitals.',
    'dashboard.ai.provider': 'Provider Risk Alert',
    'dashboard.ai.provider_desc': 'According to historical provider data, Farmacéutica Chinoin may have delivery delays. Recommended seeking alternative providers for 4 products.',
    'hospital.gen': 'Hospital General de México',
    'hospital.abc': 'Centro Médico ABC',
    'hospital.can': 'Instituto Nacional de Cancerología',
    'hospital.izt': 'Hospital Comunitario de Iztapalapa',
    'hospital.santa': 'Hospital Comunitario de Santa Fe',
    'hospital.sur': 'Centro Médico del Sur',
    'hospital.ang': 'Hospital Ángeles (México)',
    'header.all_hospitals': 'All Hospitals',
    'header.admin': 'Admin',
    'dashboard.stats.orders': 'Special Orders',
    'dashboard.stats.expiring': 'Expiring Soon',
    'dashboard.stats.suggestions': 'Purchase Suggestions',
    'dashboard.stats.reserves': 'Special Reserves',
    'dashboard.inventory_summary': 'Inventory Summary',
    'dashboard.task_list': 'Task List',
    'dashboard.notifications': 'Notifications',
    'dashboard.hospital_state': 'Hospital Inventory Status',
    'prediction.reforecast': 'Reforecast',
    'prediction.last_result': 'Last Result',
    'prediction.total_meds': 'Total Medicines',
    'prediction.accuracy': 'Forecast Accuracy',
    'prediction.optimization': 'Optimization Rate',
    'prediction.alerts': 'System Alerts',
    'prediction.detail_subtitle': 'Medicine Forecast Details',
    'prediction.replenishment_planned': 'Planned Replenishment',
    'prediction.forecast_accuracy': 'Forecast Accuracy',
    'prediction.expected_consumption': 'Expected Consumption',
    'prediction.available_stock': 'Available Stock',
    'prediction.monthly_avg_consumption': 'Monthly Avg Consumption',
    'prediction.min_stock': 'Min Stock',
    'prediction.max_stock': 'Max Stock',
    'prediction.optimal_stock': 'Optimal Stock',
    'prediction.last_entry': 'Last Entry',
    'prediction.analysis_title': 'Forecast Analysis',
    'prediction.provider': 'Provider',
    'prediction.lead_time': 'Lead Time',
    'prediction.confirm_replenishment': 'Confirm Replenishment',
    'prediction.modify_quantity': 'Modify Quantity',
    'prediction.change_provider': 'Change Provider',
    'prediction.view_details': 'View Details',
    'prediction.detail_title': 'Forecast Details',
    'params.title': 'Parameterization',
    'params.save': 'Save Changes',
    'params.reset': 'Reset',
    'params.window': 'Time Window',
    'params.safety_factor': 'Safety Factor',
    'params.seasonal': 'Seasonal Influence',
    'params.stability': 'Supply Stability',
    'params.impact_analysis': 'Impact Analysis',
    'common.view_all': 'View All',
    'common.manage': 'Manage',
    'common.back': 'Back to Dashboard',
    'common.week': 'Week',
    'common.month': 'Month',
    'common.quarter': 'Quarter',
    'day.mon': 'Mon',
    'day.tue': 'Tue',
    'day.wed': 'Wed',
    'day.thu': 'Thu',
    'day.fri': 'Fri',
    'day.sat': 'Sat',
    'day.sun': 'Sun',
    'placeholder.module_prepping': 'We are preparing the ',
    'placeholder.explore_control': ' module. Explore the Dashboard for real-time data.',
    'common.id_generic': 'Generic ID',
    'common.name_generic': 'Generic Name',
    'common.name_commercial': 'Commercial Name',
    'common.specification': 'Specification',
    'common.brand': 'Brand',
    'common.actions': 'Actions',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.details': 'Details',
    'common.add_medication': 'Add Medication',
    'common.add_pharmacy': 'Add Pharmacy',
    'common.add_provider': 'Add Provider',
    'common.total_records': 'Total {count} Records',
    'common.jump_to': 'Jump to',
    'common.records_per_page': '/ page',
    'common.month_change': 'Monthly Change',
    'common.previous_period': 'vs. previous period',
    'common.search': 'Search',
    'common.update': 'Update',
    'common.export': 'Export',
    'common.new_order': 'New Order',
    'common.total_records_count': 'Total {count} Records',
    'common.status': 'Status',
    'common.alert_type': 'Anomaly Type',
    'common.hospital': 'Hospital',
    'common.indicator': 'Indicator',
    'common.actual_value': 'Actual Value',
    'common.ref_value': 'Reference Value',
    'common.deviation_rate': 'Deviation Rate',
    'replenish.pending_approval': 'Pending Approval',
    'replenish.pending_shipment': 'Pending Shipment',
    'replenish.in_transit': 'In Transit',
    'replenish.confirm_receipt': 'Confirm Receipt',
    'replenish.order_status': 'Order Status',
    'replenish.order_no': 'Replenishment Order No.',
    'replenish.med_name': 'Medicine Name',
    'replenish.quantity_requested': 'Quantity Requested',
    'replenish.expected_delivery': 'Expected Delivery Date',
    'replenish.new_replenish_order': 'New Replenishment Order',
    'shipment.shipment_date': 'Shipment Date',
    'shipment.shipment_status': 'Shipment Status',
    'shipment.shipment_no': 'Shipment No.',
    'shipment.lot_no': 'Lot Number',
    'shipment.receiving_hospital': 'Receiving Hospital',
    'shipment.actual_quantity': 'Actual Delivered Quantity',
    'shipment.actual_delivery_date': 'Actual Shipment Date',
    'shipment.print': 'Print',
    'supply.orders_in_transit': 'Orders in Transit',
    'supply.on_time_delivery_rate': 'On-time Delivery Rate',
    'supply.orders_with_anomalies': 'Orders with Anomalies',
    'supply.late_delivery': 'Late Delivery',
    'supply.order_no': 'Replenishment Order No.',
    'supply.provider_id': 'Provider ID',
    'supply.med_info': 'Medication Information',
    'supply.order_amount': 'Order Amount',
    'supply.delivery_stats': 'Delivery Statistics by Provider',
    'supply.anomaly_analysis': 'Anomaly Order Analysis',
    'supply.delay': 'Shipment Delay',
    'supply.damaged_packaging': 'Damaged Packaging',
    'supply.incorrect_quantity': 'Incorrect Quantity',
    'supply.quality_issue': 'Quality Issue',
    'hospital.rotation_index': 'Inventory Rotation Index',
    'hospital.rupture_rate': 'Stock Rupture Rate',
    'hospital.rational_use': 'Rational Medication Use',
    'hospital.savings_rate': 'Purchase Cost Savings Rate',
    'hospital.performance_comparison': 'Hospital Performance Comparison',
    'hospital.historical_trends': 'Historical Trend Analysis',
    'hospital.anomaly_alerts': 'Performance Anomaly Alerts',
    'provider.on_time_delivery': 'On-time Delivery Rate',
    'provider.order_fulfillment': 'Order Fulfillment Rate',
    'provider.approved_quality': 'Approved Quality Rate',
    'provider.response_capacity': 'Provider Response Capacity',
    'provider.classification': 'General Provider Classification',
    'provider.trend': 'Performance Trend',
    'provider.anomaly_alerts': 'Anomaly Alerts',
    'common.reset': 'Reset',
    'common.search_btn': 'Search',
    'alerts.total': 'Total Alerts',
    'alerts.pending': 'Pending Alerts',
    'alerts.resolved': 'Resolved Alerts',
    'alerts.resolution_rate': 'Resolution Rate',
    'alerts.list_title': 'Alert List',
    'alerts.level': 'Alert Level',
    'alerts.time': 'Alert Time',
    'alerts.type': 'Alert Type',
    'alerts.med_name': 'Medicine Name',
    'alerts.stock_available': 'Stock Available',
    'alerts.stock_min': 'Min Stock',
    'alerts.critical': 'Critical',
    'alerts.important': 'Important',
    'alerts.normal': 'Normal',
    'alerts.low_stock': 'Low Stock',
    'alerts.replenish': 'Replenish',
    'alerts.sufficient': 'Sufficient',
    'pharmacy.status': 'Status',
    'pharmacy.name': 'Hospital Name',
    'pharmacy.location': 'Location/Region',
    'pharmacy.type': 'Hospital Type',
    'pharmacy.responsible': 'Responsible',
    'provider.cooperation': 'Cooperation Status',
    'provider.id': 'Provider ID',
    'provider.name': 'Provider',
    'provider.contact': 'Contact Person',
    'provider.phone': 'Contact Phone',
    'provider.address': 'Address',
    'inventory.category_filter': 'Medication Category',
    'inventory.hospital_filter': 'Hospital',
    'inventory.status_filter': 'Inventory Status',
    'inventory.search_placeholder': 'Search by Name/ID',
    'inventory.col_status': 'Inventory Status',
    'inventory.col_name': 'Medication Name',
    'inventory.col_category': 'Medication Category',
    'inventory.col_hospital': 'Hospital',
    'inventory.col_stock': 'Available Stock',
    'inventory.actions.details': 'Details',
    'inventory.actions.edit': 'Edit',
    'inventory.actions.delete': 'Delete',
    'consumption.kpi_total': 'Total Consumption',
    'consumption.kpi_avg': 'Avg Monthly Consumption',
    'consumption.kpi_annual': 'Annual Consumption',
    'consumption.trend_title': 'Consumption Trend Analysis',
    'consumption.details_title': 'Consumption Details',
    'consumption.col_med': 'Medication Name',
    'consumption.col_category': 'Medication Category',
    'consumption.col_real': 'Real Consumption',
    'consumption.col_avg': 'Avg Monthly Consumption',
    'consumption.col_annual': 'Annual Consumption',
    'inbound.id_filter': 'Inbound Date',
    'inbound.provider_filter': 'Provider',
    'inbound.status_filter': 'Inbound Status',
    'inbound.col_status': 'Status',
    'inbound.col_id': 'Inbound ID',
    'inbound.col_code': 'Medication Code',
    'inbound.col_approval': 'Approval Number',
    'inbound.col_requested': 'Requested Quantity',
    'inbound.col_provider': 'Provider ID',
    'inbound.col_date': 'Inbound Date',
    'expiry.validity_filter': 'Validity Period',
    'expiry.status_filter': 'Expiry Status',
    'expiry.col_status': 'Expiry Status',
    'expiry.col_med': 'Medication Name',
    'expiry.col_lot': 'Lot Number',
    'expiry.col_validity': 'Validity Period',
    'expiry.action_transfer': 'Transfer',
    'expiry.action_promo': 'Promotion',
    'expiry.action_return': 'Return',
    'prediction.comparison_report': 'Forecast Comparison Report',
    'prediction.cpm_forecast': 'Quantity Predicted by CPM',
    'prediction.ai_forecast': 'Quantity Predicted by PharmaLinkAI',
    'prediction.real_consumption': 'Real Consumption',
    'prediction.error_analysis': 'Error Analysis',
    'prediction.trend_comparison': 'Trend Comparison Chart',
    'prediction.col_med': 'Medication Name',
    'prediction.col_hospital': 'Hospital',
    'prediction.col_cpm_forecast': 'CPM Forecast',
    'prediction.col_cpm_error': 'CPM Error',
    'prediction.col_ai_forecast': 'AI Forecast',
    'prediction.col_ai_error': 'AI Error',
    'prediction.col_real': 'Real Consumption',
    'prediction.col_date': 'Forecast Date',
    'prediction.notice_title': 'Notice',
    'prediction.notice_desc': 'AI forecasting integrates historical trends, inventory changes, provider information, and more, offering more accurate results than traditional methods like CPM.',
    'prediction.notice_footer': 'You can adjust model parameters to improve forecast accuracy.',
    'prediction.goto_config': 'Go to Configuration',
    'ai.assistant_title': 'AI Assistant',
    'ai.history_title': 'Conversation History',
    'ai.new_chat': 'New Conversation',
    'ai.smart_assistant_header': 'IMSS Smart Assistant',
    'ai.smart_assistant_subtitle': 'Your expert in medical supply chain management',
    'ai.card_smart_answers': 'Smart answers to business questions',
    'ai.card_smart_answers_desc': 'Professional support for chain management and inventory optimization',
    'ai.card_data_analysis': 'Data Analysis Support',
    'ai.card_data_analysis_desc': 'Trend analysis, predictions, and recommendations based on historical data',
    'ai.card_report_gen': 'Report Generation',
    'ai.card_report_gen_desc': 'Automatic generation of inventory and performance reports',
    'ai.suggested_questions': 'Suggested Questions',
    'ai.input_placeholder': 'Enter your question...',
    'ai.chat_default_title': 'Inventory Forecast and Replenishment Suggestions'
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
